openSUSE/suse-module-tools

sg.conf
It's currently shipped by systemd but it's more appropriate to ship
this via a package maintained by the kernel team, see bsc#1036463.
=> Add sg.conf to force load 'sg' module at boot time

modprobe.conf/modprobe.conf.fs-blacklist, suse-module-tools.spec
As automated fuzzer testing grows in popularity, we've seen an uptick of security vulnerabilities that are in rarely used file systems. Normally this isn't an issue but the combination of user-mountable file systems and the automatic mounting of file systems on removable devices means that unprivileged users can cause the automatic loading of kernel modules to handle those operations. This feature blacklists uncommon file systems by default and allows the user to enable them if their use requires them.
=> Add file system blacklist file (fate#326832).

modprobe.conf/modprobe.conf.s390
When gpio_virtio is loaded on s390x, also load the framebuffer console (which is not built-in on s390).
=> Load fbcon automatically when needed on s390x

macros.initrd
`${//}` type substitution is not understood by shells like dash.
=> macros: avoid emitting bashisms into scriptlets

modprobe.conf/modprobe.conf.ppc64le
(bsc#1142152, ltc#176292, FATE#327775).
libnvdimm is not included in the initramfs automatically.
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> modprobe.conf: add dependency of papr_scm on libnvdimm

driver-check.sh, luarpmsort, suse-module-tools.spec, weak-modules, weak-modules2
Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1164553
Warning: COMPLETELY UNTESTED! Please tell me how to test this and I'll try to do that.
An alternative to using this new `luarpmsort` script would be to just ship a copy of the old `/usr/lib/rpm/rpmsort`, but that doesn't handle `^` and `~` properly.
=> Replace use of rpmsort with custom luarpmsort

driver-check.sh, luarpmsort, weak-modules, weak-modules2
This allows us to use luarpmsort like the legacy rpmsort program.
Also, set RPMSORT variable once in all scripts that use it.
=> luarpmsort: add -r option

suse-module-tools.spec
Make sure required packages for %post install are already installed at that
time. Use file requires where possible to be able to reduce system size for
small OS.
=> spec: rework dependencies

suse-module-tools.spec
f2fs was excluded because the on-disk format kept changing and is not
versioned. The on-disk format seems stable for now and can be enabled.
=> Enable f2fs

modprobe.conf/modprobe.conf.common
- crc32c is now an implicit softdep of libcrc32
- cifs automatically has the relevant dependencies, as does the dracut module
- libcrc32c now has crc32c as a soft-pre in its own right
- nls is compiled in, but nls_utf8 is still needed. However, it
can be provided as a pure soft-pre now
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1171065.
=> Remove more SUSE INITRD instructions

suse-module-tools.spec
We now don't support mkinitrd so we can't run on SLE11 with modutils.
=> spec file: Drop SLE11 compatibility.

lsinitrd-quick, weak-modules2
This can speed up weak-modules2 considerably. Even more so if combined with faster compression (e.g. zstd --fast).
=> Use faster lsinitrd alternative

50-kernel-uname_r.conf, boot-sysctl.service, kernel-sysctl.service, suse-module-tools.spec
We used to pull in the kernel-specific sysctl settings via an ExecStartPre
directive in systemd-sysctl.service. Create a separate service instead,
which is pulled in by systemd-sysctl. This is more transparent, and allows
more fine-grained control.
In preparation of the kernel /usr merge (bsc#1184804), create two separate
services boot-sysctl. service and kernel-sysctl.service which work with kernel
packages pre- and post- usrmerge, respectively. Only one of them will be
actually started because of a Condition directive.
"boot-sysctl.service" can be dropped when we may assume that no users keep
old kernel packages around that install their sysctl settings under /boot.
=> sysctl kernel-uname_r.conf: separate service units, kernel usr merge

weak-modules2
It's sometimes called last in other function so a return value != 0
would make those other function fail
=> weak-modules2: dlog must not return error

weak-modules2
This logic relies on the assumption that /lib/modules always resolves
to /usr/lib/modules. wm2 continues to work with /lib/modules only,
internally. All symlinks created will point to files under /lib/modules.
Thus the only point in the code where we need to account for /usr is
when we read the list of modules from stdin, and there we simply strip
off the /usr prefix, knowing that the result will still resolve to the
same file.
=> weak-modules2: accept modules under /usr/lib/modules on stdin

README.md
Fixes: f808cfb ("Import kernel scriptlets from kernel-source.")
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> README: Fix kernel scriplet description after move.

boot-sysctl.service
In containers no kernel might be installed. So make sure the service
does not fail.
=> boot-sysctl: make sure file exists

kernel-scriptlets/inkmp-script, kernel-scriptlets/kmp-script, kernel-scriptlets/rpm-script
The invocation of weak-modules2 was a bashism. We don't need
to pass any shell flags anyway. So replace it by a simple
command execution.
Alternative PR for #61.
Fixes #61.
=> kernel-scriptlets: don't pass flags to weak-modules2

driver-check.sh, unblacklist
grep 3.8 starts throwing warnings, and `egrep`/`fgrep` will be dropped long term
https://bugzilla.opensuse.org/show_bug.cgi?id=1203092
=> driver-check.sh, unblacklist: convert egrep to grep -E

kernel-scriptlets/cert-script
On certain UEFI implementations, like U-Boot's, UEFI variables cannot be
changed at runtime. As such the Linux kernel only supports a read-only efivarfs.
This patch adds a check so that an update doesn't automatically fail,
like described in boo#1201066.
Fixes #65.
=> cert-script: skip cert handling if efivarfs is not writable

suse-module-tools.spec
Allows to replace them with noops for systems based on file triggers only
=> Split kernel scriptlets into separate sub-package

kernel-scriptlets/rpm-script
It would be better if `run_bootloader()` didn't make any assumption on the supported bootloaders and let /usr/lib/bootloader/bootloader_entry figure out itself what to do with the current installation. This way other boot loaders such as systemd-boot can be more easily supported in the future.
=> rpm-script: skip run_bootloader check (boo#1208117)

kernel-scriptlets/rpm-script
rpm-script: check for regenerate-initrd-posttrans in %posttrans (boo#1212957)
If zypper is run with INITRD_IN_POSTTRANS=1 set, no initrd will be
generated. Setting this variable globally is useful in some situations,
in particular where split kernel packages like kernel-defaukt-extra are
in use. Checking the regenerate-initrd-posttrans flag is cheap if the
flag isn't present, and will fix the issue if it is.
=> rpm-script: check for regenerate-initrd-posttrans in %posttrans

regenerate-initrd-posttrans, weak-modules2
This reverts commit 60a2a14f978ea86938475de851292b988f8baf01.
Fixes bsc#1214877: 60a2a14 changed the API of regenerate-initrd-posttrans,
which may break some users of the API outside s-m-t.
=> Revert "weak-modules2: only use kernel version under /run/regenerate-initrd"

regenerate-initrd-posttrans
With a235a6e ("weak-modules2: only use kernel version under /run/regenerate-initrd")
we changed the API for programs for creating markers under
/run/regenerate-initrd. While the main user of this API is weak-modules2,
there may be external tools relying on the old behavior. Make sure
the old style, where the name of the kernel image was as marker.
Fixes: bsc#1214877
=> support old-style markers under /run/regenerate-initrd

get_dracut_drivers, suse-module-tools.spec, weak-modules2
- weak-modules2: ignore INITRD_MODULES (jsc#PED-1915)
- weak-modules2: obtain list of initrd modules from dracut (jsc#PED-1915)
=> Drop support for INITRD_MODULES (jsc#PED-1915)

suse-module-tools.spec
Added: f2fs, hfsplus, jfss2, kafs, ntfs3, orangefs, pstore, romfs, zonefs.
=> Add more modules to file system blacklist (jsc#PED-6167)

macros.initrd
mkdir is part of the coreutils package. When the post scriptlet of some
package using regenerate_initrd_post is run, the mkdir command may be
unavailable. This is non-fatal, because in all cases that matter for initrd
generation, coreutils will be part of the same transaction and will trigger
an initrd rebuild later. See boo#1217775.
Anyway, packages can use the regenerate_initrd_requires macro below to make
sure mkdir is available in their post scriptlet. Use if this macro is not
mandatory.
=> macros.initrd: %regenerate_initrd_post: don't fail if mkdir is unavailable

regenerate-initrd-posttrans
On XEN configurations, the newly created initrds must be copied to
the EFI system partition. update-bootloader --refresh (actually,
grub2-mkconfig via /etc/grub.d/20_linux_xen) will take care of this.
See bsc#1223278.
=> regenerate-initrd-posttrans: run update-bootloader --refresh for XEN

10-unblacklist.conf, suse-module-tools.spec, unblacklist
Our modprobe.d files call /usr/lib/module-init-tools/unblacklist,
causing an error message if modprobe is called on one of the blacklisted
modules. Make sure unblacklist is included in the initrd, and is a no-op.
=> Include unblacklist in initramfs (bsc#1224320)

kernel-scriptlets/cert-script, kernel-scriptlets/inkmp-script, kernel-scriptlets/kmp-script, kernel-scriptlets/rpm-script, suse-module-tools.spec
With this PR, the kernel scriptlets pass shellcheck
It contains also a few other fixes and minor code reordering.
No change of functionality.
- **rpm-script: fix minor issues reported by shellcheck**
- **rpm-script: move arm64 page-size check to separate function**
- **rpm_script: further simplify check_arm_pagesize()**
- **rpm-script: move cert-script invocation to a shell function**
- **inkmp-script: fix warnings reported by shellcheck**
- **kmp-script: fix warnings reported by shellcheck**
- **cert-script: annotate some shellcheck warnings**
=> shellcheck fixes

regenerate-initrd-posttrans
In transactional systems, regenerate-initrd-posttrans script is called outside the transaction.  In this case the current snapshot is not the default one, and we need to generate the initrd for the default one.
This patch calls sdbootutil with the --default-snapshot parameter, to refer to the correct snapshot.
=> Generate initrd for the default snapshot

README.md, dracut-posttrans, kernel-scriptlets/rpm-script, mkosi-initrd-posttrans, regenerate-initrd-posttrans, suse-module-tools.spec, weak-modules2
`mkosi` provides the `mkosi-initrd` script [1], which allows to generate initrds locally on the system. Although it is not equivalent in features to `dracut`, it's a valid alternative with its own benefits in some use cases:
- Clear ownership of bugs: no 3rd party binary (e.g. dracut) deciding what is installed from each package or even modifying them.
- Any change on a package configured to be included would automatically apply to the initrd (if the package triggers initrd rebuild).
- It attempts to shift the maintenance effort from the initrd generator to the responsible package.
Currently, `kernel-install` [2] allows to specify the initrd generator to use via `initrd_generator=` in `install.conf`, so make use of this configuration option to choose which one will be used.
[1] …
=> Add support for mkosi-initrd

kernel-scriptlets/rpm-script
- **rpm-script: fix handling of /boot/vmlinuz and /boot/initrd**
- **rpm-script: remove /boot/vmlinuz and /boot/initrd on kernel removal**
See [bsc#1207703](https://bugzilla.suse.com/show_bug.cgi?id=1207703)
=> Fix handling of /boot/initrd and /boot/vmlinuz

udevrules/60-tune-readahead.rules
Add udev rule to allow tuning the maximum readahead window for the devices.
=> udevrules: Add rule to set maximum readahead window

weak-modules2
`show-entry` return the key and the value as two different elements. This patch fix how to recover only the value part (the actual path of the initrd file)
Fix openSUSE/sdbootutil#122
=> Fix get_current_initrd parser

dracut-posttrans, mkosi-initrd-posttrans, regenerate-initrd-posttrans, weak-modules2
Before v25, mkosi-initrd failed to build initrds directly to /boot, and also to set proper permissions. Even the requested output file was a symlink to the compressed file with another extension. With v25 in Factory since snapshot 20250124, some workarounds can be removed.
Ref:
- https://github.com/systemd/mkosi/commit/3454f7bd4ef0336ec80a117d593baaef0fe53398
- https://github.com/systemd/mkosi/commit/3fe62ba52099e38920dc07cf3d3a90d048dfa954
- https://github.com/systemd/mkosi/commit/6b0dfe58f3f04264f1df5cb90b7091195913562f
=> mkosi-initrd: build initrds directly to /boot

suse-module-tools.spec
Issue reported by the systemd upstream CI:
```
2025-04-24T06:12:16.5211892Z (321/409) Installing: kernel-default-6.14.2-1.1.x86_64 [....................................................................................................
2025-04-24T06:12:16.5212812Z /usr/lib/module-init-tools/kernel-scriptlets/rpm-post: line 176: mountpoint: command not found
2025-04-24T06:12:16.5215369Z /usr/lib/module-init-tools/kernel-scriptlets/rpm-post: line 176: mountpoint: command not found
2025-04-24T06:12:16.5282697Z /usr/lib/module-init-tools/weak-modules2: line 887: getopt: command not found
2025-04-24T06:12:16.5287258Z Usage:
2025-04-24T06:12:16.5298235Z     weak-modules2 --add-kmp kmp-name-version-release
2025-04-24T06:12:16.5302921Z     weak-modules2 --remove-kmp kmp-name < module-list …
```
=> spec file: add missing util-linux requirement
